server:
  port: 8080

spring:
  application:
    name: bank-cards

  datasource:
    url: ${BANK_DB_URL}/${BANK_DB_NAME}
    username: ${BANK_DB_USER}
    password: ${BANK_DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 0

  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
    tracer: TRACE

debug: true

app:
  crypto:
    key: ${APP_CRYPTO_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

